#+title: Ox-Zola
#+author: Giovanni Crisalfi
[[https://www.gnu.org/licenses/gpl-3.0][https://img.shields.io/badge/License-GPL%20v3-blue.svg]]

Ox-zola is an Org exporter backend that exports Org mode to Markdown with TOML frontmatter compatible with [[https://www.getzola.org/][the Zola static site generator]].

*Drop-in replacement for ox-hugo when targeting Zola.* If you're migrating your blog from Hugo to Zola, you can keep your existing Org files with =HUGO_*= keywords unchanged! Just switch to ox-zola and your exports will produce Zola-compatible output.

* Quick start

Configure your Zola site in your Emacs config:

#+begin_src emacs-lisp
(setq ox-zola-base-dir "~/my-zola-site")
(setq ox-zola-section "posts")  ; default section
#+end_src

Or configure per-file with keywords:

#+begin_src org
#+zola_base_dir: /path/to/your/zola/project
#+zola_section: posts
#+end_src

Write your posts as Org headings:

#+begin_src org
,* My First Post
:PROPERTIES:
:EXPORT_FILE_NAME: my-first-post
:END:
This is my first post written in Org-mode!
#+end_src

Export with the Org export dispatcher (=M-x org-export-dispatch= or =C-c C-e=). The Zola backend appears under the =Z= key:

#+begin_example
 [Z] Export to Zola Markdown
     [z] Subtree or File to Md file            [Z] File to a temporary Md buffer
     [O] Subtree or File to Md file and open   [f] File to Md file
     [A] All subtrees (or File) to Md file(s)  [o] File to Md file and open
#+end_example

It builds on top of [[https://github.com/kaushalmodi/ox-hugo][ox-hugo]], so all ox-hugo features work: subtree exports, property inheritance, WIM detection, and more. See the [[https://ox-hugo.scripter.co/][ox-hugo documentation]] for the full feature set.

** Adding taxonomies

Use Org tags for taxonomies:

#+begin_src org
,* My First Post :@blogging:emacs:
#+end_src

This creates a category =blogging= and a tag =emacs=.

Or use file-level keywords:

#+begin_src org
#+zola_categories: blogging
#+zola_tags: emacs org-mode
#+end_src

Both produce proper Zola frontmatter:

#+begin_src toml
[taxonomies]
categories = ["blogging"]
tags = ["emacs", "org-mode"]
#+end_src

** Page bundles

To create a page bundle with assets in the same directory:

#+begin_src org
,* My First Post :@blogging:emacs:
:PROPERTIES:
:EXPORT_HUGO_SECTION: posts/my-first-post
:EXPORT_FILE_NAME: index
:END:
#+end_src

* Migrating from Hugo to Zola

If you're switching your blog from Hugo to Zola:

1. Keep your existing Org files - =HUGO_*= keywords work unchanged
2. Replace your config:
   #+begin_src emacs-lisp
   ;; Before (ox-hugo)
   (require 'ox-hugo)
   (setq org-hugo-base-dir "~/blog")

   ;; After (ox-zola)
   (require 'ox-zola)
   (setq ox-zola-base-dir "~/blog")
   #+end_src
3. Use =ox-zola-export-*= instead of =org-hugo-export-*=

ox-zola automatically transforms the output for Zola:

| ox-hugo (Hugo)         | ox-zola (Zola)         |
|------------------------+------------------------|
| =tags = [...]= at root | =[taxonomies]= section |
| =lastmod=              | =updated=              |
| =layout=               | =template=             |
| ~{{< shortcode >}}~    | ~{{ shortcode() }}~    |
| =relref= shortcodes    | =@/= path syntax       |

If you have different websites generated with Zola and Hugo, you're covered. =ox-zola= doesn't break =ox-hugo=: both can coexist!

* Installation

** With Straight

#+begin_src emacs-lisp
(use-package ox-zola
  :straight (ox-zola :host github :repo "gicrisf/ox-zola"))
#+end_src

** With built-in =:vc= (Emacs 29+)

#+begin_src emacs-lisp
(use-package ox-zola
  :vc (:url "https://github.com/gicrisf/ox-zola"
            :rev :newest
            :branch "main"))
#+end_src

** With Doom

In =~/.config/doom/packages.el=:

#+begin_src emacs-lisp
(package! ox-zola :recipe (:host github :repo "gicrisf/ox-zola"))
#+end_src

In =~/.config/doom/config.el=:

#+begin_src emacs-lisp
(use-package! ox-zola)
#+end_src

Then run =doom sync=.

* Donate

Did you find this package useful? Buy me a coffee!

[[https://ko-fi.com/V7V425BFU][https://ko-fi.com/img/githubbutton_sm.svg]]

* License

Open sourced under the [[./LICENSE][GPL-3.0 license]].
